<a href="https://colab.research.google.com/github/MinhDuy187IT23224/PythonNangCao/blob/main/Lab02/Chuong9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
celegans_phenotypes = ['Emb','Him', 'Unc', 'Lon', 'Dpy', 'Sma']
for i in celegans_phenotypes:
  print(i)

Emb
Him
Unc
Lon
Dpy
Sma


In [3]:
half_live = [87.74, 24110.0, 6537.0, 14.4, 376000.0]
for half_live in half_live:
  print(half_live, end="  ")

87.74  24110.0  6537.0  14.4  376000.0  

In [4]:
whales = [5, 4, 7, 3, 2, 3, 2, 6, 4, 2, 1, 7, 1, 3]
more_whales = []
for i in whales:
  more_whales.append(i+1)
print(more_whales)

[6, 5, 8, 4, 3, 4, 3, 7, 5, 3, 2, 8, 2, 4]


In [5]:
alkaline_earth_metals = [[4,12,20,38,56,88],[9.012,24.305,40.078,87.62,137.327,226]]

In [6]:
for alkaline_earth_metals in alkaline_earth_metals:
  print(alkaline_earth_metals)

[4, 12, 20, 38, 56, 88]
[9.012, 24.305, 40.078, 87.62, 137.327, 226]


In [7]:

alkaline_earth_metals = [[4,12,20,38,56,88],[9.012,24.305,40.078,87.62,137.327,226]]
[x for number_and_weight in alkaline_earth_metals for x in number_and_weight]

[4, 12, 20, 38, 56, 88, 9.012, 24.305, 40.078, 87.62, 137.327, 226]

In [8]:
def mystery_function(values):
  result = []
  for sublist in values:
    result.append([sublist[0]])
    for i in sublist[1:]:
      result[-1].insert(0, i)
  return result
mystery_function([[1,2,3],[4,5,6]])

[[3, 2, 1], [6, 5, 4]]

In [9]:

text = " "
while text.lower() != "quit":
  text = input("Please enter (or 'quit' to exit): ")
  if text == "quit":
    print("Exiting program")
  elif text == "CO2":
    print("Cacbonic")
  elif text == "C6H12O6":
    print("Glucozo")
  else:
    print("Unknown")

Please enter (or 'quit' to exit): qiut
Unknown
Please enter (or 'quit' to exit): exut
Unknown
Please enter (or 'quit' to exit): exit
Unknown
Please enter (or 'quit' to exit): quit
Exiting program


In [10]:
sum = 0
country_populations =[1295,23,7,3,47,21]
for i in country_populations:
  sum = sum + i
print(sum)

1396


In [11]:
import numpy as np
rat_1 = np.random.randint(10,size=10)
rat_2 = np.random.randint(10,size=10)
print(rat_1)
print(rat_2)
if (rat_1[0] > rat_2[0]):
  print("Rat 1 weighed more than Rat 2 on day 1")
else:
  print("Rat 2 weighed more than Rat 1 on day 1")

[1 3 2 3 6 7 9 5 7 5]
[9 3 1 0 6 0 1 0 7 1]
Rat 2 weighed more than Rat 1 on day 1


In [12]:
print(rat_1)
print(rat_2)
if rat_1[0] > rat_2[0] and rat_1[-1] > rat_2[-1]:
  print("Rat 1 remained heavier than Rat 2.")
else:
  print("Rat 2 became heavier than Rat 1.")

[1 3 2 3 6 7 9 5 7 5]
[9 3 1 0 6 0 1 0 7 1]
Rat 2 became heavier than Rat 1.


In [13]:
if rat_1[0] > rat_2[0]:
  if rat_1[-1] > rat_2[-1]:
    print("Rat 1 remained heavier than Rat 2.")
  else:
    print("Rat 2 became heavier than Rat 1.")
else:
  print("Rat 2 became heavier than Rat 1.")

Rat 2 became heavier than Rat 1.


In [14]:
for i in range(33,50):
  print(i)

33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49


In [15]:
for i in range(1,11):
  print(i,end=" ")

1 2 3 4 5 6 7 8 9 10 

In [16]:
sum = 0
count = 0
for i in range(2,23):
  sum = sum + i
  count = count + 1
  average = sum / count
print(average)

12.0


In [17]:
def remove_neg(num_list):
  for i in num_list:
    if num_list[i] < 0:
      del num_list[i]
  print(num_list)
remove_neg([1, 2, 3, -3, 6, -1, -3, 1])

[1, 2, 3, 6, -3, 1]


In [18]:
for i in range(1,8):
  s = " "
  for j in range(1,i+1):
    s = s + " T"
  print(s)

  T
  T T
  T T T
  T T T T
  T T T T T
  T T T T T T
  T T T T T T T


In [19]:
n = 8
k = 2*n - 2
for i in range(1,n):
  for j in range(1,k):
    print(end = " ")
  k = k -2
  for j in range(1,i+1):
    print("T", end = " ")
  print("\r")

             T 
           T T 
         T T T 
       T T T T 
     T T T T T 
   T T T T T T 
 T T T T T T T 


In [20]:
i = 1
while i < 8:
  print("T"*i )
  i += 1

T
TT
TTT
TTTT
TTTTT
TTTTTT
TTTTTTT


In [21]:
i = 1
while i< 8:
  print(" "*(8-i),"T"*i)
  i += 1

        T
       TT
      TTT
     TTTT
    TTTTT
   TTTTTT
  TTTTTTT


In [22]:

rat_1_weight = 10.0
rat_1_rate = 0.04
last_weight = 0.25*rat_1_weight + rat_1_weight
weeks = 0
result = rat_1_weight
while result < last_weight:
  result += result * rat_1_rate
  weeks += 1
print(weeks)

6


In [23]:
rat_1_weight = 5
rat_2_weight = 5
rat_1_rate = 0.04
rat_2_weight = 0.04
last_weight_1 = 0.04*rat_1_weight + rat_1_weight
last_weight_2 = 0.04*rat_2_weight + rat_2_weight
weeks = 0
result = rat_2_weight
while result < last_weight_2:
  result += result*0.1
  weeks += 1
print(weeks)

1
